version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

  eshop.client.authorizationserver:
    image: ${DOCKER_REGISTRY-}eshop.client.authorizationserver:${TAG:-latest}
    build:
      context: .
      dockerfile: src/EShop.Client.AuthorizationServer/Dockerfile
    depends_on:
      - sqlserver
