useAks: false 
dockerRegistry: "" 
imagesTag: ""
imagePullSecretName: ""
ingressControllerNamespaceName: "ingress-nginx" 

azure: 
  tenantId: ""
  catalogApiUmiClientId: ""
  employeeManagementUmiClientId: ""
  customerAuthserverUmiClientId: ""
  catalogSqlServerName: ""
  employeeSqlServerName: ""
  customerSqlServerName: ""
  orderingSqlServerName: ""
  sagaSqlServerName: ""
  basketApiUmiClientId: ""
  orderingApiUmiClientId: ""
  paymentProcessorUmiClientId: ""
  sagaProcessorUmiClientId: ""
  serviceBusNamespaceName: ""
  redisCacheName: ""

eshop_ingress:
  appName: eshop-ingress
  ingressClassName: nginx
  eshopDnsName:  eshop.example.com 
  eshopEmployeePortalDnsName: eshop-employee-portal.example.com 

catalog_api:
  appName: catalog-api
  replicaCount: 1
  serviceAccountName: catalog-api-sa
  image:
    repository: eshop.catalog.api  
  env:
    ASPNETCORE_ENVIRONMENT: "Development"
    initDbOnStartup: "true"  
  resources:
    memory: "200Mi"
    cpu: "200m"

customer_authserver:
  appName: customer-authserver
  replicaCount: 1
  serviceAccountName: customer-authserver-sa
  image:
    repository: eshop.customer.authorizationserver
  env:
    ASPNETCORE_ENVIRONMENT: "Development"
    initDbOnStartup: "true"
    clientId: "customer-portal"
    displayName: "public spa"  
  resources:
    memory: "200Mi"
    cpu: "200m"

customer_portal:
  appName: customer-portal
  replicaCount: 1
  image:
    repository: eshop.ui.customerportal    
  resources:
    memory: "100Mi"
    cpu: "100m"

employee_portal:
  appName: employee-portal
  replicaCount: 1
  image:
    repository: eshop.ui.employeeportal    
  resources:
    memory: "100Mi"
    cpu: "100m"

employeemanagement_api:
  appName: employeemanagement-api
  replicaCount: 1
  serviceAccountName: employeemanagement-api-sa
  image:
    repository: eshop.employeemanagement.api
  env:
    ASPNETCORE_ENVIRONMENT: "Development"
    initDbOnStartup: "true"  
  resources:
    memory: "200Mi"
    cpu: "100m"

employeemanagement_authserver:
  appName: employeemanagement-authserver
  replicaCount: 1
  serviceAccountName: employeemanagement-authserver-sa
  image:
    repository:  eshop.employeemanagement.authorizationserver
  env:
    ASPNETCORE_ENVIRONMENT: "Development"
    clientId: "employee-portal"
    displayName: "public spa"  
  resources:
    memory: "200Mi"
    cpu: "100m"

employee_external_authserver:
  issuer: ''
  metadataAddress: ''
  audience: ''

basket_api:
  appName: basket-api
  replicaCount: 1
  serviceAccountName: basket-api-sa
  image: 
    repository: eshop.basket.api
  env:
    ASPNETCORE_ENVIRONMENT: "Development"
  resources:
    memory: "200Mi"
    cpu: "100m"

ordering_api:
  appName: ordering-api
  replicaCount: 1
  serviceAccountName: ordering-api-sa
  image:
    repository: eshop.ordering.api
  env:
    ASPNETCORE_ENVIRONMENT: "Development"
    initDbOnStartup: "true"
  resources:
    memory: "200Mi"
    cpu: "100m"

payment_processor:
  appName: payment-processor
  replicaCount: 1
  serviceAccountName: payment-processor-sa
  image:
    repository: eshop.payment.processor
  env:
    ASPNETCORE_ENVIRONMENT: "Development"
    payment__processPayment: "True"
  resources:
    memory: "200Mi"
    cpu: "100m"

saga_processor:
  appName: saga-processor
  replicaCount: 1
  serviceAccountName: saga-processor-sa
  image:
    repository: eshop.saga.processor
  env:
    ASPNETCORE_ENVIRONMENT: "Development"
    initDbOnStartup: "true"
  resources:
    memory: "200Mi"
    cpu: "100m"

sql_db:
  appName: sql-db
  image:
    repository: mcr.microsoft.com/mssql/server:2022-CU4-ubuntu-20.04
    pullPolicy: IfNotPresent  
  env:
    mssqlPassword: "E*AmPleP@ssw0rd"
  storage:
    pvcName: sql-api-pvc
    pvcStorage: 1Gi
  resources:
    memory: "2000Mi"
    cpu: "2000m"
  servicePort: 1433

redis:
  appName: redis
  image: redis:7.0.15-alpine3.20
  resources:
    memory: "200Mi"
    cpu: "100m"
  servicePort: 6379

rabbitmq:
  appName: rabbitmq
  image: rabbitmq:3.13-management-alpine
  resources:
    memory: "200Mi"
    cpu: "100m"
  ports:
    service: 5672
    management: 15672