version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

  eshop.ordering.api:
    image: ${DOCKER_REGISTRY-}eshop.ordering.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/EShop.Ordering.Api/Dockerfile
    depends_on:
      - sqlserver
