apiVersion: v1
kind: Service
metadata:
  name:  client-authserver
spec:
  selector:
    app:  client-authserver
  type:  LoadBalancer
  ports:
  - protocol: 'TCP'
    port:  5058
    targetPort:  80