apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-authserver
spec:
  selector:
    matchLabels:
      app: client-authserver
  template:
    metadata:
      labels:
        app: client-authserver
    spec:
      containers:
      - name: client-authserver
        image: eshop.client.authorizationserver:latest     
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ASPNETCORE_URLS
            value: http://+:80
          - name: ConnectionStrings__clientDbConnectionString
            value: Server=tcp:api-db.default;Integrated Security=false;Initial Catalog=eshop.client.Db;User Id=sa;password=E*AmPleP@ssw0rd;TrustServerCertificate=true
          - name: initDbOnStartup
            value: "true"
          - name: clients__0__clientOrigin
            value: https://client-portal.example.com
          - name: clients__0__clientId
            value: client-portal
          - name: clients__0__displayName
            value: "public spa"
          - name: ASPNETCORE_APPL_PATH
            value: authorize
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
          - containerPort: 80