apiVersion: v1
kind: Service
metadata:
  name:  client-portal
spec:
  selector:
    app:  client-portal
  type:  LoadBalancer
  ports:
  - protocol: 'TCP'
    port:  4201
    targetPort:  80