apiVersion: v1
kind: Service
metadata:
  name:  employeemanagement-api
spec:
  selector:
    app:  employeemanagement-api
  type:  LoadBalancer
  ports:
  - protocol: 'TCP'
    port:  5158
    targetPort:  80