apiVersion: apps/v1
kind: Deployment
metadata:
  name: employeemanagement-api
spec:
  selector:
    matchLabels:
      app: employeemanagement-api
  template:
    metadata:
      labels:
        app: employeemanagement-api
    spec:
      containers:
      - name: employeemanagement-api
        image: eshop.employeemanagement.api:latest    
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ASPNETCORE_URLS
            value: http://+:80
          - name: ConnectionStrings__employeeDbConnectionString
            value: Server=tcp:api-db.default;Integrated Security=false;Initial Catalog=eshop.employee.Db;User Id=sa;password=E*AmPleP@ssw0rd;TrustServerCertificate=true
          - name: initDbOnStartup
            value: "true"
          - name: clientOrigin
            value: https://employee-portal.example.com
          - name: JWTSettings__Issuer
            value: https://employee-portal.example.com/authorize
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
          - containerPort: 80