apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-portal
  template:
    metadata:
      labels:
        app: employee-portal
    spec:
      containers:
        - name: employee-portal
          image: eshop.ui.employeeportal:latest
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            initialDelaySeconds: 5       
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"