apiVersion: v1
kind: Service
metadata:
  name:  employee-portal
spec:
  selector:
    app:  employee-portal
  type:  LoadBalancer
  ports:
  - protocol: 'TCP'
    port:  4202
    targetPort:  80