apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2$3
  name:  {{ .Values.eshop_ingress.appName }}    
  labels:
    name:  {{ .Values.eshop_ingress.appName }}    
spec:
  ingressClassName: {{ .Values.eshop_ingress.ingressClassName }} 
  rules:
  - host: {{ .Values.eshop_ingress.eshopDnsName }}
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/()()(.*)"
        backend:
          service:
            name: {{ .Values.customer_portal.appName }}    
            port: 
              number: 80
      - pathType: ImplementationSpecific
        path: "/catalog(/|$)(.*)"
        backend:
          service:
            name: {{ .Values.catalog_api.appName }}  
            port: 
              number: 80
      - pathType: ImplementationSpecific
        path:  "/(basket/)(api)(.*)"
        backend:
          service:
            name: {{ .Values.basket_api.appName }}  
            port: 
              number: 80
      - pathType: ImplementationSpecific
        path:  "/(ordering/)(api)(.*)"
        backend:
          service:
            name: {{ .Values.ordering_api.appName }}  
            port: 
              number: 80
      - pathType: ImplementationSpecific
        path: /()(authorize)(.*)
        backend:
          service:
            name: {{ .Values.customer_authserver.appName }}
            port: 
              number: 80
  - host: {{ .Values.eshop_ingress.eshopEmployeePortalDnsName }}
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/()()(.*)"
        backend:
          service:
            name: {{ .Values.employee_portal.appName }}
            port: 
              number: 80
      - pathType: ImplementationSpecific
        path: "/catalog(/|$)(.*)"
        backend:
          service:
            name: {{ .Values.catalog_api.appName }}
            port: 
              number: 80
      - pathType: ImplementationSpecific
        path: /()(authorize)(.*)
        backend:
          service:
            name: {{ .Values.employeemanagement_authserver.appName }}
            port: 
              number: 80
      - pathType: ImplementationSpecific
        path: "/(employee-management/)(api)(.*)"
        backend:
          service:
            name: {{ .Values.employeemanagement_api.appName }}
            port: 
              number: 80
  
