{{ if not .Values.useAks -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.sql_db.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.sql_db.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.sql_db.appName }}    
    spec:     
      securityContext:
        fsGroup: 10001
      containers:
      - name: {{ .Values.sql_db.appName }}
        image: "{{ .Values.sql_db.image.repository }}"
        imagePullPolicy: {{ .Values.sql_db.image.pullPolicy }}
        env:
          - name: MSSQL_SA_PASSWORD
            value: {{ .Values.sql_db.env.mssqlPassword }}
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_PID
            value: Express
        ports:
        - containerPort: 1433
        resources:
          limits:
            memory:  {{ .Values.sql_db.resources.memory }}
            cpu:  {{ .Values.sql_db.resources.cpu }}
        volumeMounts:
        - mountPath: /var/opt/mssql
          name: sql-api-db-pvc
      volumes:
      - name: sql-api-db-pvc
        persistentVolumeClaim:
          claimName: {{ .Values.sql_db.storage.pvcName }}
---

apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.sql_db.appName }}
spec:
  selector:
    app:  {{ .Values.sql_db.appName }}
  type:  ClusterIP
  ports:
  - protocol: 'TCP'
    port:  {{ .Values.sql_db.servicePort }}
    targetPort:  1433

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.sql_db.storage.pvcName }}
spec:
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.sql_db.storage.pvcStorage }}
  accessModes:
    - ReadWriteOnce

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sql-db-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.sql_db.appName }}
  ingress: 
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.catalog_api.appName }}
    - podSelector:
        matchLabels:
          app: {{ .Values.customer_authserver.appName }}
    - podSelector:
        matchLabels:
          app: {{ .Values.employeemanagement_api.appName }}
    - podSelector:
        matchLabels:
          app: {{ .Values.employeemanagement_authserver.appName }}
    - podSelector:
        matchLabels:
          app: {{ .Values.ordering_api.appName }}
    - podSelector:
        matchLabels:
          app: {{ .Values.saga_processor.appName }}

{{- end }}