name: Deploy Docker Image Web App

on:
  workflow_call:
    inputs:
      serviceName:
        required: true
        type: string
      webAppName:
        required: true
        type: string
      dockerHubUserName:
        required: true
        type: string
      dockerImageTag:
        required: true
        type: string
      repositoryName:
        required: true
        type: string
        
    secrets:
      AZURE_CREDENTIALS:
        required: true
      DOCKER_REGISTRY_SERVER_PASSWORD:
        required: true     
  
jobs:
  deploy:

    env:
      dockerRegistryUrl: 'https://index.docker.io/v1/'

    runs-on: ubuntu-latest
    
    steps:
    - name: Azure Login
      uses: Azure/login@v1.6.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}      

    - name: Set ${{ inputs.serviceName }} Web App Docker Authentication
      uses: Azure/appservice-settings@v1
      with:
       app-name: ${{ inputs.webAppName }}
       app-settings-json: |
         [
             {
                 "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
                 "value": "${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}",
                 "slotSetting": false
             },
             {
                 "name": "DOCKER_REGISTRY_SERVER_URL",
                 "value": "${{ inputs.dockerRegistryUrl }}",
                 "slotSetting": false
             },
             {
                 "name": "DOCKER_REGISTRY_SERVER_USERNAME",
                 "value": "${{ inputs.dockerHubUserName  }}",
                 "slotSetting": false
             }
         ]
    
    - name: Deploy ${{ inputs.serviceName }} Web App
      uses: Azure/webapps-deploy@v3.0.0
      with:
        app-name: ${{ inputs.webAppName }}
        images: ${{ inputs.dockerHubUserName  }}/${{ inputs.repositoryName }}:${{ inputs.dockerImageTag }}       
        restart: true            
           
